
import type { Customer } from '@/types/crm';

export const demoCustomers: Customer[] = [
  {
    id: "demo-cust-001",
    xero_contact_id: "demo-xero-001",
    name: "Alpha Plumbing Services",
    email_address: "contact@alphaplumbing.com",
    phone_numbers: [{ PhoneType: "MOBILE", PhoneNumber: "+64-21-234-5678" }],
    addresses: [{ AddressLine1: "123 Main St, Springfield, IL 62701" }],
    contact_status: "ACTIVE",
    is_supplier: false,
    is_customer: true,
    contact_groups: [],
    website: "www.alphaplumbing.com",
    contact_persons: [],
    sales_tracking_categories: [],
    purchases_tracking_categories: [],
    created_at: "2023-01-15T10:00:00Z",
    updated_at: "2024-12-01T10:00:00Z"
  },
  {
    id: "demo-cust-002",
    xero_contact_id: "demo-xero-002",
    name: "Beta Electrical Co",
    email_address: "info@betaelectrical.com",
    phone_numbers: [{ PhoneType: "MOBILE", PhoneNumber: "+64-27-345-6789" }],
    addresses: [{ AddressLine1: "456 Oak Ave, Springfield, IL 62702" }],
    contact_status: "ACTIVE",
    is_supplier: false,
    is_customer: true,
    contact_groups: [],
    website: "www.betaelectrical.com",
    contact_persons: [],
    sales_tracking_categories: [],
    purchases_tracking_categories: [],
    created_at: "2023-02-10T10:00:00Z",
    updated_at: "2024-12-01T10:00:00Z"
  },
  {
    id: "demo-cust-003",
    xero_contact_id: "demo-xero-003",
    name: "Gamma Landscaping",
    email_address: "service@gammalandscaping.com",
    phone_numbers: [{ PhoneType: "MOBILE", PhoneNumber: "+64-22-456-7890" }],
    addresses: [{ AddressLine1: "789 Pine Rd, Springfield, IL 62703" }],
    contact_status: "ACTIVE",
    is_supplier: false,
    is_customer: true,
    contact_groups: [],
    website: "www.gammalandscaping.com",
    contact_persons: [],
    sales_tracking_categories: [],
    purchases_tracking_categories: [],
    created_at: "2023-03-05T10:00:00Z",
    updated_at: "2024-12-01T10:00:00Z"
  },
  {
    id: "demo-cust-004",
    xero_contact_id: "demo-xero-004",
    name: "Delta HVAC Solutions",
    email_address: "hello@deltahvac.com",
    phone_numbers: [{ PhoneType: "MOBILE", PhoneNumber: "+64-21-567-8901" }],
    addresses: [{ AddressLine1: "321 Elm St, Springfield, IL 62704" }],
    contact_status: "ACTIVE",
    is_supplier: false,
    is_customer: true,
    contact_groups: [],
    website: "www.deltahvac.com",
    contact_persons: [],
    sales_tracking_categories: [],
    purchases_tracking_categories: [],
    created_at: "2023-04-12T10:00:00Z",
    updated_at: "2024-12-01T10:00:00Z"
  },
  {
    id: "demo-cust-005",
    xero_contact_id: "demo-xero-005",
    name: "Echo Roofing & Repairs",
    email_address: "jobs@echoroofing.com",
    phone_numbers: [{ PhoneType: "MOBILE", PhoneNumber: "+64-27-678-9012" }],
    addresses: [{ AddressLine1: "654 Maple Dr, Springfield, IL 62705" }],
    contact_status: "ACTIVE",
    is_supplier: false,
    is_customer: true,
    contact_groups: [],
    contact_persons: [],
    sales_tracking_categories: [],
    purchases_tracking_categories: [],
    created_at: "2023-05-18T10:00:00Z",
    updated_at: "2024-12-01T10:00:00Z"
  },
  {
    id: "demo-cust-006",
    xero_contact_id: "demo-xero-006",
    name: "Foxtrot Painting Services",
    email_address: "contact@foxtrotpainting.com",
    phone_numbers: [{ PhoneType: "MOBILE", PhoneNumber: "+64-22-789-0123" }],
    addresses: [{ AddressLine1: "987 Cedar Ln, Springfield, IL 62706" }],
    contact_status: "ACTIVE",
    is_supplier: false,
    is_customer: true,
    contact_groups: [],
    contact_persons: [],
    sales_tracking_categories: [],
    purchases_tracking_categories: [],
    created_at: "2023-06-22T10:00:00Z",
    updated_at: "2024-12-01T10:00:00Z"
  },
  {
    id: "demo-cust-007",
    xero_contact_id: "demo-xero-007",
    name: "Golf Property Maintenance",
    email_address: "info@golfproperty.com",
    phone_numbers: [{ PhoneType: "MOBILE", PhoneNumber: "+64-21-890-1234" }],
    addresses: [{ AddressLine1: "147 Birch Ave, Springfield, IL 62707" }],
    contact_status: "ACTIVE",
    is_supplier: false,
    is_customer: true,
    contact_groups: [],
    contact_persons: [],
    sales_tracking_categories: [],
    purchases_tracking_categories: [],
    created_at: "2023-07-08T10:00:00Z",
    updated_at: "2024-12-01T10:00:00Z"
  },
  {
    id: "demo-cust-008",
    xero_contact_id: "demo-xero-008",
    name: "Hotel Cleaning Services",
    email_address: "service@hotelcleaning.com",
    phone_numbers: [{ PhoneType: "MOBILE", PhoneNumber: "+64-27-901-2345" }],
    addresses: [{ AddressLine1: "258 Willow St, Springfield, IL 62708" }],
    contact_status: "ACTIVE",
    is_supplier: false,
    is_customer: true,
    contact_groups: [],
    contact_persons: [],
    sales_tracking_categories: [],
    purchases_tracking_categories: [],
    created_at: "2023-08-14T10:00:00Z",
    updated_at: "2024-12-01T10:00:00Z"
  },
  {
    id: "demo-cust-009",
    xero_contact_id: "demo-xero-009",
    name: "India Carpet Cleaning",
    email_address: "bookings@indiacarpet.com",
    phone_numbers: [{ PhoneType: "MOBILE", PhoneNumber: "+64-22-012-3456" }],
    addresses: [{ AddressLine1: "369 Poplar Rd, Springfield, IL 62709" }],
    contact_status: "ACTIVE",
    is_supplier: false,
    is_customer: true,
    contact_groups: [],
    contact_persons: [],
    sales_tracking_categories: [],
    purchases_tracking_categories: [],
    created_at: "2023-09-03T10:00:00Z",
    updated_at: "2024-12-01T10:00:00Z"
  },
  {
    id: "demo-cust-010",
    xero_contact_id: "demo-xero-010",
    name: "Juliet Home Security",
    email_address: "install@julietsecurity.com",
    phone_numbers: [{ PhoneType: "MOBILE", PhoneNumber: "+64-21-123-4567" }],
    addresses: [{ AddressLine1: "741 Spruce Way, Springfield, IL 62710" }],
    contact_status: "ACTIVE",
    is_supplier: false,
    is_customer: true,
    contact_groups: [],
    contact_persons: [],
    sales_tracking_categories: [],
    purchases_tracking_categories: [],
    created_at: "2023-10-11T10:00:00Z",
    updated_at: "2024-12-01T10:00:00Z"
  },
  {
    id: "demo-cust-011",
    xero_contact_id: "demo-xero-011",
    name: "Kilo Floor Refinishing",
    email_address: "services@kilofloor.com",
    phone_numbers: [{ PhoneType: "MOBILE", PhoneNumber: "+64-27-234-5678" }],
    addresses: [{ AddressLine1: "852 Ash Blvd, Springfield, IL 62711" }],
    contact_status: "ACTIVE",
    is_supplier: false,
    is_customer: true,
    contact_groups: [],
    contact_persons: [],
    sales_tracking_categories: [],
    purchases_tracking_categories: [],
    created_at: "2023-11-05T10:00:00Z",
    updated_at: "2024-12-01T10:00:00Z"
  },
  {
    id: "demo-cust-012",
    xero_contact_id: "demo-xero-012",
    name: "Lima Pool Services",
    email_address: "contact@limapool.com",
    phone_numbers: [{ PhoneType: "MOBILE", PhoneNumber: "+64-22-345-6789" }],
    addresses: [{ AddressLine1: "963 Palm Dr, Springfield, IL 62712" }],
    contact_status: "ACTIVE",
    is_supplier: false,
    is_customer: true,
    contact_groups: [],
    contact_persons: [],
    sales_tracking_categories: [],
    purchases_tracking_categories: [],
    created_at: "2023-12-01T10:00:00Z",
    updated_at: "2024-12-01T10:00:00Z"
  },
  {
    id: "demo-cust-013",
    xero_contact_id: "demo-xero-013",
    name: "Mike Appliance Repair",
    email_address: "repair@mikeappliance.com",
    phone_numbers: [{ PhoneType: "MOBILE", PhoneNumber: "+64-21-456-7890" }],
    addresses: [{ AddressLine1: "741 Cherry St, Springfield, IL 62713" }],
    contact_status: "ACTIVE",
    is_supplier: false,
    is_customer: true,
    contact_groups: [],
    contact_persons: [],
    sales_tracking_categories: [],
    purchases_tracking_categories: [],
    created_at: "2024-01-08T10:00:00Z",
    updated_at: "2024-12-01T10:00:00Z"
  },
  {
    id: "demo-cust-014",
    xero_contact_id: "demo-xero-014",
    name: "November Window Cleaning",
    email_address: "clean@novemberwindow.com",
    phone_numbers: [{ PhoneType: "MOBILE", PhoneNumber: "+64-27-567-8901" }],
    addresses: [{ AddressLine1: "159 Walnut Ave, Springfield, IL 62714" }],
    contact_status: "ACTIVE",
    is_supplier: false,
    is_customer: true,
    contact_groups: [],
    contact_persons: [],
    sales_tracking_categories: [],
    purchases_tracking_categories: [],
    created_at: "2024-02-14T10:00:00Z",
    updated_at: "2024-12-01T10:00:00Z"
  },
  {
    id: "demo-cust-015",
    xero_contact_id: "demo-xero-015",
    name: "Oscar Pest Control",
    email_address: "exterminate@oscarpest.com",
    phone_numbers: [{ PhoneType: "MOBILE", PhoneNumber: "+64-22-678-9012" }],
    addresses: [{ AddressLine1: "357 Hickory Ln, Springfield, IL 62715" }],
    contact_status: "ACTIVE",
    is_supplier: false,
    is_customer: true,
    contact_groups: [],
    contact_persons: [],
    sales_tracking_categories: [],
    purchases_tracking_categories: [],
    created_at: "2024-03-20T10:00:00Z",
    updated_at: "2024-12-01T10:00:00Z"
  },
  {
    id: "demo-cust-016",
    xero_contact_id: "demo-xero-016",
    name: "Papa Handyman Services",
    email_address: "fixes@papahandyman.com",
    phone_numbers: [{ PhoneType: "MOBILE", PhoneNumber: "+64-21-789-0123" }],
    addresses: [{ AddressLine1: "468 Dogwood Rd, Springfield, IL 62716" }],
    contact_status: "ACTIVE",
    is_supplier: false,
    is_customer: true,
    contact_groups: [],
    contact_persons: [],
    sales_tracking_categories: [],
    purchases_tracking_categories: [],
    created_at: "2024-04-25T10:00:00Z",
    updated_at: "2024-12-01T10:00:00Z"
  },
  {
    id: "demo-cust-017",
    xero_contact_id: "demo-xero-017",
    name: "Quebec Concrete Works",
    email_address: "pour@quebecconcrete.com",
    phone_numbers: [{ PhoneType: "MOBILE", PhoneNumber: "+64-27-890-1234" }],
    addresses: [{ AddressLine1: "579 Magnolia Way, Springfield, IL 62717" }],
    contact_status: "ACTIVE",
    is_supplier: false,
    is_customer: true,
    contact_groups: [],
    contact_persons: [],
    sales_tracking_categories: [],
    purchases_tracking_categories: [],
    created_at: "2024-05-30T10:00:00Z",
    updated_at: "2024-12-01T10:00:00Z"
  },
  {
    id: "demo-cust-018",
    xero_contact_id: "demo-xero-018",
    name: "Romeo Tree Service",
    email_address: "trim@romeotree.com",
    phone_numbers: [{ PhoneType: "MOBILE", PhoneNumber: "+64-22-901-2345" }],
    addresses: [{ AddressLine1: "680 Sycamore St, Springfield, IL 62718" }],
    contact_status: "ACTIVE",
    is_supplier: false,
    is_customer: true,
    contact_groups: [],
    contact_persons: [],
    sales_tracking_categories: [],
    purchases_tracking_categories: [],
    created_at: "2024-06-12T10:00:00Z",
    updated_at: "2024-12-01T10:00:00Z"
  },
  {
    id: "demo-cust-019",
    xero_contact_id: "demo-xero-019",
    name: "Sierra Moving Company",
    email_address: "move@sierramoving.com",
    phone_numbers: [{ PhoneType: "MOBILE", PhoneNumber: "+64-21-012-3456" }],
    addresses: [{ AddressLine1: "791 Redwood Dr, Springfield, IL 62719" }],
    contact_status: "ACTIVE",
    is_supplier: false,
    is_customer: true,
    contact_groups: [],
    contact_persons: [],
    sales_tracking_categories: [],
    purchases_tracking_categories: [],
    created_at: "2024-07-18T10:00:00Z",
    updated_at: "2024-12-01T10:00:00Z"
  },
  {
    id: "demo-cust-020",
    xero_contact_id: "demo-xero-020",
    name: "Tango Auto Detailing",
    email_address: "detail@tangoauto.com",
    phone_numbers: [{ PhoneType: "MOBILE", PhoneNumber: "+64-27-123-4567" }],
    addresses: [{ AddressLine1: "802 Cypress Ave, Springfield, IL 62720" }],
    contact_status: "ACTIVE",
    is_supplier: false,
    is_customer: true,
    contact_groups: [],
    contact_persons: [],
    sales_tracking_categories: [],
    purchases_tracking_categories: [],
    created_at: "2024-08-24T10:00:00Z",
    updated_at: "2024-12-01T10:00:00Z"
  }
];
