
import type { Invoice } from '@/types/crm';

// Utility functions for generating recent dates
const getRandomDaysAgo = (minDays: number = 1, maxDays: number = 30): number => {
  return Math.floor(Math.random() * (maxDays - minDays + 1)) + minDays;
};

const addDays = (date: Date, days: number): Date => {
  const result = new Date(date);
  result.setDate(result.getDate() + days);
  return result;
};

const formatDate = (date: Date): string => {
  return date.toISOString().split('T')[0];
};

const formatDateTime = (date: Date): string => {
  return date.toISOString();
};

export const demoInvoices: Invoice[] = [
  {
    id: "demo-inv-001",
    xero_invoice_id: "demo-xero-inv-001",
    xero_contact_id: "demo-xero-001",
    invoice_number: "INV-2024-001",
    invoice_type: "ACCREC",
    invoice_status: "PAID",
    line_amount_types: "Exclusive",
    invoice_date: formatDate(addDays(new Date(), -getRandomDaysAgo(1, 30))),
    due_date: formatDate(addDays(new Date(), -getRandomDaysAgo(1, 30) + 30)),
    sub_total: 850.00,
    total_tax: 85.00,
    total: 935.00,
    total_discount: 0.00,
    amount_due: 0.00,
    amount_paid: 935.00,
    amount_credited: 0.00,
    fully_paid_on_date: formatDate(addDays(new Date(), -getRandomDaysAgo(1, 25))),
    work_description: "OE-24-1101 123 Main St | Emergency pipe repair in basement | Replaced burst copper pipe section | Labour 4 hours | Materials: copper pipe, fittings, solder",
    service_keywords: ["emergency repair", "plumbing", "pipe replacement", "basement work"],
    line_items: [
      { Description: "Emergency plumbing call-out", Quantity: 1, UnitAmount: 150.00, LineAmount: 150.00 },
      { Description: "Copper pipe replacement - 6ft section", Quantity: 1, UnitAmount: 250.00, LineAmount: 250.00 },
      { Description: "Labour - 4 hours", Quantity: 4, UnitAmount: 112.50, LineAmount: 450.00 }
    ],
    created_at: formatDateTime(addDays(new Date(), -getRandomDaysAgo(1, 30))),
    updated_at: formatDateTime(addDays(new Date(), -getRandomDaysAgo(1, 25)))
  },
  {
    id: "demo-inv-002",
    xero_invoice_id: "demo-xero-inv-002",
    xero_contact_id: "demo-xero-002",
    invoice_number: "INV-2024-002",
    invoice_type: "ACCREC",
    invoice_status: "AUTHORISED",
    line_amount_types: "Exclusive",
    invoice_date: formatDate(addDays(new Date(), -getRandomDaysAgo(1, 30))),
    due_date: formatDate(addDays(new Date(), -getRandomDaysAgo(1, 30) + 30)),
    sub_total: 1250.00,
    total_tax: 125.00,
    total: 1375.00,
    total_discount: 0.00,
    amount_due: 1375.00,
    amount_paid: 0.00,
    amount_credited: 0.00,
    work_description: "OE-24-1102 456 Oak Ave | Kitchen electrical upgrade | Installed new circuit breakers and GFCI outlets | Labour 6 hours | Materials: breakers, outlets, wiring",
    service_keywords: ["electrical upgrade", "kitchen renovation", "GFCI installation", "circuit breakers"],
    line_items: [
      { Description: "Circuit breaker panel upgrade", Quantity: 1, UnitAmount: 400.00, LineAmount: 400.00 },
      { Description: "GFCI outlets installation", Quantity: 4, UnitAmount: 75.00, LineAmount: 300.00 },
      { Description: "Labour - 6 hours", Quantity: 6, UnitAmount: 91.67, LineAmount: 550.00 }
    ],
    created_at: formatDateTime(addDays(new Date(), -getRandomDaysAgo(1, 30))),
    updated_at: formatDateTime(addDays(new Date(), -getRandomDaysAgo(1, 30)))
  },
  {
    id: "demo-inv-003",
    xero_invoice_id: "demo-xero-inv-003",
    xero_contact_id: "demo-xero-003",
    invoice_number: "INV-2024-003",
    invoice_type: "ACCREC",
    invoice_status: "PAID",
    line_amount_types: "Exclusive",
    invoice_date: formatDate(addDays(new Date(), -getRandomDaysAgo(1, 30))),
    due_date: formatDate(addDays(new Date(), -getRandomDaysAgo(1, 30) + 30)),
    sub_total: 2800.00,
    total_tax: 280.00,
    total: 3080.00,
    total_discount: 0.00,
    amount_due: 0.00,
    amount_paid: 3080.00,
    amount_credited: 0.00,
    fully_paid_on_date: formatDate(addDays(new Date(), -getRandomDaysAgo(1, 25))),
    work_description: "OE-24-1003 789 Pine Rd | Fall landscape cleanup and winter prep | Leaf removal, pruning, winterization | Labour 2 days | Materials: mulch, plant covers",
    service_keywords: ["landscape cleanup", "fall maintenance", "pruning", "winterization"],
    line_items: [
      { Description: "Fall cleanup - leaf removal", Quantity: 1, UnitAmount: 800.00, LineAmount: 800.00 },
      { Description: "Tree and shrub pruning", Quantity: 1, UnitAmount: 600.00, LineAmount: 600.00 },
      { Description: "Winter prep and mulching", Quantity: 1, UnitAmount: 500.00, LineAmount: 500.00 },
      { Description: "Labour - 16 hours", Quantity: 16, UnitAmount: 56.25, LineAmount: 900.00 }
    ],
    created_at: formatDateTime(addDays(new Date(), -getRandomDaysAgo(1, 30))),
    updated_at: formatDateTime(addDays(new Date(), -getRandomDaysAgo(1, 25)))
  },
  {
    id: "demo-inv-004",
    xero_invoice_id: "demo-xero-inv-004",
    xero_contact_id: "demo-xero-004",
    invoice_number: "INV-2024-004",
    invoice_type: "ACCREC",
    invoice_status: "PAID",
    line_amount_types: "Exclusive",
    invoice_date: formatDate(addDays(new Date(), -getRandomDaysAgo(1, 30))),
    due_date: formatDate(addDays(new Date(), -getRandomDaysAgo(1, 30) + 30)),
    sub_total: 1650.00,
    total_tax: 165.00,
    total: 1815.00,
    total_discount: 0.00,
    amount_due: 0.00,
    amount_paid: 1815.00,
    amount_credited: 0.00,
    fully_paid_on_date: formatDate(addDays(new Date(), -getRandomDaysAgo(1, 25))),
    work_description: "OE-24-0912 321 Elm St | Annual HVAC maintenance and filter replacement | System inspection, cleaning, tune-up | Labour 3 hours | Materials: filters, lubricants",
    service_keywords: ["HVAC maintenance", "system inspection", "filter replacement", "tune-up"],
    line_items: [
      { Description: "HVAC system inspection", Quantity: 1, UnitAmount: 200.00, LineAmount: 200.00 },
      { Description: "Filter replacement - premium filters", Quantity: 6, UnitAmount: 25.00, LineAmount: 150.00 },
      { Description: "System cleaning and tune-up", Quantity: 1, UnitAmount: 300.00, LineAmount: 300.00 },
      { Description: "Labour - 8 hours", Quantity: 8, UnitAmount: 125.00, LineAmount: 1000.00 }
    ],
    created_at: formatDateTime(addDays(new Date(), -getRandomDaysAgo(1, 30))),
    updated_at: formatDateTime(addDays(new Date(), -getRandomDaysAgo(1, 25)))
  },
  {
    id: "demo-inv-005",
    xero_invoice_id: "demo-xero-inv-005",
    xero_contact_id: "demo-xero-005",
    invoice_number: "INV-2024-005",
    invoice_type: "ACCREC",
    invoice_status: "AUTHORISED",
    line_amount_types: "Exclusive",
    invoice_date: formatDate(addDays(new Date(), -getRandomDaysAgo(1, 30))),
    due_date: formatDate(addDays(new Date(), -getRandomDaysAgo(1, 30) + 30)),
    sub_total: 4200.00,
    total_tax: 420.00,
    total: 4620.00,
    total_discount: 0.00,
    amount_due: 4620.00,
    amount_paid: 0.00,
    amount_credited: 0.00,
    work_description: "OE-24-1125 654 Maple Dr | Emergency roof repair after storm damage | Shingle replacement, flashing repair | Labour 2 days | Materials: shingles, flashing, sealant",
    service_keywords: ["emergency repair", "roof repair", "storm damage", "shingle replacement"],
    line_items: [
      { Description: "Emergency roof inspection", Quantity: 1, UnitAmount: 300.00, LineAmount: 300.00 },
      { Description: "Shingle replacement - 20 squares", Quantity: 20, UnitAmount: 85.00, LineAmount: 1700.00 },
      { Description: "Flashing repair and replacement", Quantity: 1, UnitAmount: 500.00, LineAmount: 500.00 },
      { Description: "Labour - 16 hours", Quantity: 16, UnitAmount: 103.75, LineAmount: 1660.00 }
    ],
    created_at: formatDateTime(addDays(new Date(), -getRandomDaysAgo(1, 30))),
    updated_at: formatDateTime(addDays(new Date(), -getRandomDaysAgo(1, 30)))
  },
  {
    id: "demo-inv-006",
    xero_invoice_id: "demo-xero-inv-006",
    xero_contact_id: "demo-xero-006",
    invoice_number: "INV-2024-006",
    invoice_type: "ACCREC",
    invoice_status: "PAID",
    line_amount_types: "Exclusive",
    invoice_date: formatDate(addDays(new Date(), -getRandomDaysAgo(1, 30))),
    due_date: formatDate(addDays(new Date(), -getRandomDaysAgo(1, 30) + 30)),
    sub_total: 1800.00,
    total_tax: 180.00,
    total: 1980.00,
    total_discount: 0.00,
    amount_due: 0.00,
    amount_paid: 1980.00,
    amount_credited: 0.00,
    fully_paid_on_date: formatDate(addDays(new Date(), -getRandomDaysAgo(1, 25))),
    work_description: "OE-24-0815 987 Cedar Ln | Interior painting - living room and bedrooms | Surface prep, primer, two coats | Labour 3 days | Materials: paint, primer, supplies",
    service_keywords: ["interior painting", "surface preparation", "residential work", "multi-room"],
    line_items: [
      { Description: "Surface preparation", Quantity: 1, UnitAmount: 400.00, LineAmount: 400.00 },
      { Description: "Premium paint - 5 gallons", Quantity: 5, UnitAmount: 60.00, LineAmount: 300.00 },
      { Description: "Primer and supplies", Quantity: 1, UnitAmount: 200.00, LineAmount: 200.00 },
      { Description: "Labour - 18 hours", Quantity: 18, UnitAmount: 50.00, LineAmount: 900.00 }
    ],
    created_at: formatDateTime(addDays(new Date(), -getRandomDaysAgo(1, 30))),
    updated_at: formatDateTime(addDays(new Date(), -getRandomDaysAgo(1, 25)))
  },
  {
    id: "demo-inv-007",
    xero_invoice_id: "demo-xero-inv-007",
    xero_contact_id: "demo-xero-007",
    invoice_number: "INV-2024-007",
    invoice_type: "ACCREC",
    invoice_status: "PAID",
    line_amount_types: "Exclusive",
    invoice_date: formatDate(addDays(new Date(), -getRandomDaysAgo(1, 30))),
    due_date: formatDate(addDays(new Date(), -getRandomDaysAgo(1, 30) + 30)),
    sub_total: 950.00,
    total_tax: 95.00,
    total: 1045.00,
    total_discount: 0.00,
    amount_due: 0.00,
    amount_paid: 1045.00,
    amount_credited: 0.00,
    fully_paid_on_date: formatDate(addDays(new Date(), -getRandomDaysAgo(1, 25))),
    work_description: "OE-24-0720 147 Birch Ave | Monthly property maintenance package | Lawn care, pressure washing, gutter cleaning | Labour 1 day | Materials: cleaning supplies",
    service_keywords: ["property maintenance", "lawn care", "pressure washing", "gutter cleaning"],
    line_items: [
      { Description: "Lawn mowing and edging", Quantity: 1, UnitAmount: 200.00, LineAmount: 200.00 },
      { Description: "Pressure washing - driveway and walkways", Quantity: 1, UnitAmount: 300.00, LineAmount: 300.00 },
      { Description: "Gutter cleaning and inspection", Quantity: 1, UnitAmount: 150.00, LineAmount: 150.00 },
      { Description: "Labour - 6 hours", Quantity: 6, UnitAmount: 50.00, LineAmount: 300.00 }
    ],
    created_at: formatDateTime(addDays(new Date(), -getRandomDaysAgo(1, 30))),
    updated_at: formatDateTime(addDays(new Date(), -getRandomDaysAgo(1, 25)))
  },
  {
    id: "demo-inv-008",
    xero_invoice_id: "demo-xero-inv-008",
    xero_contact_id: "demo-xero-008",
    invoice_number: "INV-2024-008",
    invoice_type: "ACCREC",
    invoice_status: "PAID",
    line_amount_types: "Exclusive",
    invoice_date: formatDate(addDays(new Date(), -getRandomDaysAgo(1, 30))),
    due_date: formatDate(addDays(new Date(), -getRandomDaysAgo(1, 30) + 30)),
    sub_total: 750.00,
    total_tax: 75.00,
    total: 825.00,
    total_discount: 0.00,
    amount_due: 0.00,
    amount_paid: 825.00,
    amount_credited: 0.00,
    fully_paid_on_date: formatDate(addDays(new Date(), -getRandomDaysAgo(1, 25))),
    work_description: "OE-24-1110 258 Willow St | Deep cleaning service for commercial office | Floor cleaning, window washing, sanitization | Labour 1 day | Materials: cleaning supplies",
    service_keywords: ["commercial cleaning", "deep cleaning", "office sanitization", "window washing"],
    line_items: [
      { Description: "Floor deep cleaning - 2000 sq ft", Quantity: 1, UnitAmount: 300.00, LineAmount: 300.00 },
      { Description: "Window washing - interior/exterior", Quantity: 20, UnitAmount: 8.00, LineAmount: 160.00 },
      { Description: "Sanitization and disinfection", Quantity: 1, UnitAmount: 150.00, LineAmount: 150.00 },
      { Description: "Labour - 8 hours", Quantity: 8, UnitAmount: 17.50, LineAmount: 140.00 }
    ],
    created_at: formatDateTime(addDays(new Date(), -getRandomDaysAgo(1, 30))),
    updated_at: formatDateTime(addDays(new Date(), -getRandomDaysAgo(1, 25)))
  },
  {
    id: "demo-inv-009",
    xero_invoice_id: "demo-xero-inv-009",
    xero_contact_id: "demo-xero-009",
    invoice_number: "INV-2024-009",
    invoice_type: "ACCREC",
    invoice_status: "AUTHORISED",
    line_amount_types: "Exclusive",
    invoice_date: formatDate(addDays(new Date(), -getRandomDaysAgo(1, 30))),
    due_date: formatDate(addDays(new Date(), -getRandomDaysAgo(1, 30) + 30)),
    sub_total: 650.00,
    total_tax: 65.00,
    total: 715.00,
    total_discount: 0.00,
    amount_due: 715.00,
    amount_paid: 0.00,
    amount_credited: 0.00,
    work_description: "OE-24-1201 369 Poplar Rd | Professional carpet cleaning - whole house | Steam cleaning, stain treatment, deodorizing | Labour 4 hours | Materials: cleaning solutions",
    service_keywords: ["carpet cleaning", "steam cleaning", "stain removal", "residential service"],
    line_items: [
      { Description: "Steam cleaning - 800 sq ft carpet", Quantity: 1, UnitAmount: 400.00, LineAmount: 400.00 },
      { Description: "Stain treatment and protection", Quantity: 1, UnitAmount: 100.00, LineAmount: 100.00 },
      { Description: "Deodorizing treatment", Quantity: 1, UnitAmount: 50.00, LineAmount: 50.00 },
      { Description: "Labour - 4 hours", Quantity: 4, UnitAmount: 25.00, LineAmount: 100.00 }
    ],
    created_at: formatDateTime(addDays(new Date(), -getRandomDaysAgo(1, 30))),
    updated_at: formatDateTime(addDays(new Date(), -getRandomDaysAgo(1, 30)))
  },
  {
    id: "demo-inv-010",
    xero_invoice_id: "demo-xero-inv-010",
    xero_contact_id: "demo-xero-010",
    invoice_number: "INV-2024-010",
    invoice_type: "ACCREC",
    invoice_status: "PAID",
    line_amount_types: "Exclusive",
    invoice_date: formatDate(addDays(new Date(), -getRandomDaysAgo(1, 30))),
    due_date: formatDate(addDays(new Date(), -getRandomDaysAgo(1, 30) + 30)),
    sub_total: 2200.00,
    total_tax: 220.00,
    total: 2420.00,
    total_discount: 0.00,
    amount_due: 0.00,
    amount_paid: 2420.00,
    amount_credited: 0.00,
    fully_paid_on_date: formatDate(addDays(new Date(), -getRandomDaysAgo(1, 25))),
    work_description: "OE-24-0615 741 Spruce Way | Home security system installation | Cameras, sensors, control panel setup | Labour 1 day | Materials: security equipment",
    service_keywords: ["security installation", "camera system", "home automation", "sensor installation"],
    line_items: [
      { Description: "Security cameras - 4 units", Quantity: 4, UnitAmount: 200.00, LineAmount: 800.00 },
      { Description: "Control panel and sensors", Quantity: 1, UnitAmount: 600.00, LineAmount: 600.00 },
      { Description: "Installation and setup", Quantity: 1, UnitAmount: 400.00, LineAmount: 400.00 },
      { Description: "Labour - 8 hours", Quantity: 8, UnitAmount: 50.00, LineAmount: 400.00 }
    ],
    created_at: formatDateTime(addDays(new Date(), -getRandomDaysAgo(1, 30))),
    updated_at: formatDateTime(addDays(new Date(), -getRandomDaysAgo(1, 25)))
  },
  {
    id: "demo-inv-011",
    xero_invoice_id: "demo-xero-inv-011",
    xero_contact_id: "demo-xero-011",
    invoice_number: "INV-2024-011",
    invoice_type: "ACCREC",
    invoice_status: "PAID",
    line_amount_types: "Exclusive",
    invoice_date: formatDate(addDays(new Date(), -getRandomDaysAgo(1, 30))),
    due_date: formatDate(addDays(new Date(), -getRandomDaysAgo(1, 30) + 30)),
    sub_total: 3200.00,
    total_tax: 320.00,
    total: 3520.00,
    total_discount: 0.00,
    amount_due: 0.00,
    amount_paid: 3520.00,
    amount_credited: 0.00,
    fully_paid_on_date: formatDate(addDays(new Date(), -getRandomDaysAgo(1, 25))),
    work_description: "OE-24-0510 852 Ash Blvd | Hardwood floor refinishing - entire main floor | Sanding, staining, polyurethane | Labour 3 days | Materials: stain, polyurethane",
    service_keywords: ["floor refinishing", "hardwood restoration", "sanding", "staining"],
    line_items: [
      { Description: "Floor sanding - 1200 sq ft", Quantity: 1, UnitAmount: 1500.00, LineAmount: 1500.00 },
      { Description: "Staining and finishing", Quantity: 1, UnitAmount: 800.00, LineAmount: 800.00 },
      { Description: "Materials - stain and polyurethane", Quantity: 1, UnitAmount: 400.00, LineAmount: 400.00 },
      { Description: "Labour - 24 hours", Quantity: 24, UnitAmount: 20.83, LineAmount: 500.00 }
    ],
    created_at: formatDateTime(addDays(new Date(), -getRandomDaysAgo(1, 30))),
    updated_at: formatDateTime(addDays(new Date(), -getRandomDaysAgo(1, 25)))
  },
  {
    id: "demo-inv-012",
    xero_invoice_id: "demo-xero-inv-012",
    xero_contact_id: "demo-xero-011",
    invoice_number: "INV-2024-012",
    invoice_type: "ACCPAY",
    invoice_status: "PAID",
    line_amount_types: "Exclusive",
    invoice_date: "2024-05-08",
    due_date: "2024-05-18",
    sub_total: 400.00,
    total_tax: 40.00,
    total: 440.00,
    total_discount: 0.00,
    amount_due: 0.00,
    amount_paid: 440.00,
    amount_credited: 0.00,
    fully_paid_on_date: "2024-05-15",
    work_description: "Equipment rental for floor refinishing project",
    service_keywords: ["equipment rental", "floor sanders", "supplies"],
    line_items: [
      { Description: "Floor sander rental - 3 days", Quantity: 3, UnitAmount: 100.00, LineAmount: 300.00 },
      { Description: "Edger rental - 3 days", Quantity: 3, UnitAmount: 33.33, LineAmount: 100.00 }
    ],
    created_at: "2024-05-08T09:00:00Z",
    updated_at: "2024-05-15T10:00:00Z"
  },
  {
    id: "demo-inv-013",
    xero_invoice_id: "demo-xero-inv-013",
    xero_contact_id: "demo-xero-012",
    invoice_number: "INV-2024-013",
    invoice_type: "ACCREC",
    invoice_status: "PAID",
    line_amount_types: "Exclusive",
    invoice_date: formatDate(addDays(new Date(), -getRandomDaysAgo(1, 30))),
    due_date: formatDate(addDays(new Date(), -getRandomDaysAgo(1, 30) + 30)),
    sub_total: 1800.00,
    total_tax: 180.00,
    total: 1980.00,
    total_discount: 0.00,
    amount_due: 0.00,
    amount_paid: 1980.00,
    amount_credited: 0.00,
    fully_paid_on_date: formatDate(addDays(new Date(), -getRandomDaysAgo(1, 25))),
    work_description: "OE-24-0805 963 Palm Dr | Pool opening and seasonal maintenance | Equipment check, chemical balancing, cleaning | Labour 6 hours | Materials: chemicals",
    service_keywords: ["pool opening", "seasonal maintenance", "chemical balancing", "equipment service"],
    line_items: [
      { Description: "Pool opening service", Quantity: 1, UnitAmount: 400.00, LineAmount: 400.00 },
      { Description: "Equipment inspection and service", Quantity: 1, UnitAmount: 500.00, LineAmount: 500.00 },
      { Description: "Chemical balancing", Quantity: 1, UnitAmount: 200.00, LineAmount: 200.00 },
      { Description: "Labour - 6 hours", Quantity: 6, UnitAmount: 116.67, LineAmount: 700.00 }
    ],
    created_at: formatDateTime(addDays(new Date(), -getRandomDaysAgo(1, 30))),
    updated_at: formatDateTime(addDays(new Date(), -getRandomDaysAgo(1, 25)))
  },
  {
    id: "demo-inv-014",
    xero_invoice_id: "demo-xero-inv-014",
    xero_contact_id: "demo-xero-012",
    invoice_number: "INV-2024-014",
    invoice_type: "ACCREC",
    invoice_status: "PAID",
    line_amount_types: "Exclusive",
    invoice_date: formatDate(addDays(new Date(), -getRandomDaysAgo(1, 30))),
    due_date: formatDate(addDays(new Date(), -getRandomDaysAgo(1, 30) + 30)),
    sub_total: 650.00,
    total_tax: 65.00,
    total: 715.00,
    total_discount: 0.00,
    amount_due: 0.00,
    amount_paid: 715.00,
    amount_credited: 0.00,
    fully_paid_on_date: formatDate(addDays(new Date(), -getRandomDaysAgo(1, 25))),
    work_description: "OE-24-0915 963 Palm Dr | Monthly pool maintenance | Cleaning, chemical testing, equipment check | Labour 3 hours | Materials: chemicals",
    service_keywords: ["monthly maintenance", "pool cleaning", "chemical testing", "equipment check"],
    line_items: [
      { Description: "Pool cleaning and skimming", Quantity: 1, UnitAmount: 200.00, LineAmount: 200.00 },
      { Description: "Chemical testing and adjustment", Quantity: 1, UnitAmount: 150.00, LineAmount: 150.00 },
      { Description: "Equipment maintenance", Quantity: 1, UnitAmount: 100.00, LineAmount: 100.00 },
      { Description: "Labour - 3 hours", Quantity: 3, UnitAmount: 66.67, LineAmount: 200.00 }
    ],
    created_at: formatDateTime(addDays(new Date(), -getRandomDaysAgo(1, 30))),
    updated_at: formatDateTime(addDays(new Date(), -getRandomDaysAgo(1, 25)))
  },
  {
    id: "demo-inv-015",
    xero_invoice_id: "demo-xero-inv-015",
    xero_contact_id: "demo-xero-012",
    invoice_number: "INV-2024-015",
    invoice_type: "ACCPAY",
    invoice_status: "PAID",
    line_amount_types: "Exclusive",
    invoice_date: "2024-08-01",
    due_date: "2024-08-11",
    sub_total: 300.00,
    total_tax: 30.00,
    total: 330.00,
    total_discount: 0.00,
    amount_due: 0.00,
    amount_paid: 330.00,
    amount_credited: 0.00,
    fully_paid_on_date: "2024-08-08",
    work_description: "Pool chemical supplies for seasonal opening",
    service_keywords: ["chemical supplies", "pool chemicals", "seasonal supplies"],
    line_items: [
      { Description: "Chlorine tablets - 50 lbs", Quantity: 2, UnitAmount: 75.00, LineAmount: 150.00 },
      { Description: "pH adjustment chemicals", Quantity: 1, UnitAmount: 100.00, LineAmount: 100.00 },
      { Description: "Algaecide", Quantity: 1, UnitAmount: 50.00, LineAmount: 50.00 }
    ],
    created_at: "2024-08-01T10:00:00Z",
    updated_at: "2024-08-08T12:00:00Z"
  },
  {
    id: "demo-inv-016",
    xero_invoice_id: "demo-xero-inv-016",
    xero_contact_id: "demo-xero-013",
    invoice_number: "INV-2024-016",
    invoice_type: "ACCREC",
    invoice_status: "PAID",
    line_amount_types: "Exclusive",
    invoice_date: formatDate(addDays(new Date(), -getRandomDaysAgo(1, 30))),
    due_date: formatDate(addDays(new Date(), -getRandomDaysAgo(1, 30) + 30)),
    sub_total: 420.00,
    total_tax: 42.00,
    total: 462.00,
    total_discount: 0.00,
    amount_due: 0.00,
    amount_paid: 462.00,
    amount_credited: 0.00,
    fully_paid_on_date: formatDate(addDays(new Date(), -getRandomDaysAgo(1, 25))),
    work_description: "OE-24-0708 741 Cherry St | Dishwasher repair | Replaced faulty pump and door seal | Labour 2 hours | Materials: pump, door seal",
    service_keywords: ["appliance repair", "dishwasher repair", "pump replacement", "door seal"],
    line_items: [
      { Description: "Service call and diagnosis", Quantity: 1, UnitAmount: 120.00, LineAmount: 120.00 },
      { Description: "Dishwasher pump replacement", Quantity: 1, UnitAmount: 180.00, LineAmount: 180.00 },
      { Description: "Door seal replacement", Quantity: 1, UnitAmount: 80.00, LineAmount: 80.00 },
      { Description: "Labour - 2 hours", Quantity: 2, UnitAmount: 20.00, LineAmount: 40.00 }
    ],
    created_at: formatDateTime(addDays(new Date(), -getRandomDaysAgo(1, 30))),
    updated_at: formatDateTime(addDays(new Date(), -getRandomDaysAgo(1, 25)))
  },
  {
    id: "demo-inv-017",
    xero_invoice_id: "demo-xero-inv-017",
    xero_contact_id: "demo-xero-013",
    invoice_number: "INV-2024-017",
    invoice_type: "ACCREC",
    invoice_status: "AUTHORISED",
    line_amount_types: "Exclusive",
    invoice_date: formatDate(addDays(new Date(), -getRandomDaysAgo(1, 30))),
    due_date: formatDate(addDays(new Date(), -getRandomDaysAgo(1, 30) + 30)),
    sub_total: 350.00,
    total_tax: 35.00,
    total: 385.00,
    total_discount: 0.00,
    amount_due: 385.00,
    amount_paid: 0.00,
    amount_credited: 0.00,
    work_description: "OE-24-1128 741 Cherry St | Refrigerator repair | Replaced defrost timer and cleaned coils | Labour 1.5 hours | Materials: defrost timer",
    service_keywords: ["refrigerator repair", "defrost timer", "coil cleaning", "maintenance"],
    line_items: [
      { Description: "Service call and diagnosis", Quantity: 1, UnitAmount: 120.00, LineAmount: 120.00 },
      { Description: "Defrost timer replacement", Quantity: 1, UnitAmount: 100.00, LineAmount: 100.00 },
      { Description: "Coil cleaning service", Quantity: 1, UnitAmount: 80.00, LineAmount: 80.00 },
      { Description: "Labour - 1.5 hours", Quantity: 1.5, UnitAmount: 33.33, LineAmount: 50.00 }
    ],
    created_at: formatDateTime(addDays(new Date(), -getRandomDaysAgo(1, 30))),
    updated_at: formatDateTime(addDays(new Date(), -getRandomDaysAgo(1, 30)))
  },
  {
    id: "demo-inv-018",
    xero_invoice_id: "demo-xero-inv-018",
    xero_contact_id: "demo-xero-014",
    invoice_number: "INV-2024-018",
    invoice_type: "ACCREC",
    invoice_status: "PAID",
    line_amount_types: "Exclusive",
    invoice_date: formatDate(addDays(new Date(), -getRandomDaysAgo(1, 30))),
    due_date: formatDate(addDays(new Date(), -getRandomDaysAgo(1, 30) + 30)),
    sub_total: 280.00,
    total_tax: 28.00,
    total: 308.00,
    total_discount: 0.00,
    amount_due: 0.00,
    amount_paid: 308.00,
    amount_credited: 0.00,
    fully_paid_on_date: formatDate(addDays(new Date(), -getRandomDaysAgo(1, 25))),
    work_description: "OE-24-0620 159 Walnut Ave | Residential window cleaning | Interior and exterior windows, screens | Labour 4 hours | Materials: cleaning supplies",
    service_keywords: ["window cleaning", "residential service", "interior exterior", "screen cleaning"],
    line_items: [
      { Description: "Window cleaning - 24 windows", Quantity: 24, UnitAmount: 8.00, LineAmount: 192.00 },
      { Description: "Screen cleaning", Quantity: 12, UnitAmount: 5.00, LineAmount: 60.00 },
      { Description: "Labour - 4 hours", Quantity: 4, UnitAmount: 7.00, LineAmount: 28.00 }
    ],
    created_at: formatDateTime(addDays(new Date(), -getRandomDaysAgo(1, 30))),
    updated_at: formatDateTime(addDays(new Date(), -getRandomDaysAgo(1, 25)))
  },
  {
    id: "demo-inv-019",
    xero_invoice_id: "demo-xero-inv-019",
    xero_contact_id: "demo-xero-014",
    invoice_number: "INV-2024-019",
    invoice_type: "ACCREC",
    invoice_status: "PAID",
    line_amount_types: "Exclusive",
    invoice_date: formatDate(addDays(new Date(), -getRandomDaysAgo(1, 30))),
    due_date: formatDate(addDays(new Date(), -getRandomDaysAgo(1, 30) + 30)),
    sub_total: 320.00,
    total_tax: 32.00,
    total: 352.00,
    total_discount: 0.00,
    amount_due: 0.00,
    amount_paid: 352.00,
    amount_credited: 0.00,
    fully_paid_on_date: formatDate(addDays(new Date(), -getRandomDaysAgo(1, 25))),
    work_description: "OE-24-1015 159 Walnut Ave | Fall window cleaning and gutter cleaning | Interior/exterior windows, gutter cleaning | Labour 5 hours | Materials: cleaning supplies",
    service_keywords: ["fall cleaning", "window cleaning", "gutter cleaning", "seasonal service"],
    line_items: [
      { Description: "Window cleaning - 24 windows", Quantity: 24, UnitAmount: 8.00, LineAmount: 192.00 },
      { Description: "Gutter cleaning and inspection", Quantity: 1, UnitAmount: 100.00, LineAmount: 100.00 },
      { Description: "Labour - 5 hours", Quantity: 5, UnitAmount: 5.60, LineAmount: 28.00 }
    ],
    created_at: formatDateTime(addDays(new Date(), -getRandomDaysAgo(1, 30))),
    updated_at: formatDateTime(addDays(new Date(), -getRandomDaysAgo(1, 25)))
  },
  {
    id: "demo-inv-020",
    xero_invoice_id: "demo-xero-inv-020",
    xero_contact_id: "demo-xero-015",
    invoice_number: "INV-2024-020",
    invoice_type: "ACCREC",
    invoice_status: "PAID",
    line_amount_types: "Exclusive",
    invoice_date: formatDate(addDays(new Date(), -getRandomDaysAgo(1, 30))),
    due_date: formatDate(addDays(new Date(), -getRandomDaysAgo(1, 30) + 30)),
    sub_total: 350.00,
    total_tax: 35.00,
    total: 385.00,
    total_discount: 0.00,
    amount_due: 0.00,
    amount_paid: 385.00,
    amount_credited: 0.00,
    fully_paid_on_date: formatDate(addDays(new Date(), -getRandomDaysAgo(1, 25))),
    work_description: "OE-24-0410 357 Hickory Ln | Quarterly pest control treatment | Interior and exterior treatment, ant control | Labour 2 hours | Materials: pesticides",
    service_keywords: ["pest control", "quarterly treatment", "ant control", "interior exterior"],
    line_items: [
      { Description: "Interior pest treatment", Quantity: 1, UnitAmount: 150.00, LineAmount: 150.00 },
      { Description: "Exterior perimeter treatment", Quantity: 1, UnitAmount: 120.00, LineAmount: 120.00 },
      { Description: "Ant control treatment", Quantity: 1, UnitAmount: 60.00, LineAmount: 60.00 },
      { Description: "Labour - 2 hours", Quantity: 2, UnitAmount: 10.00, LineAmount: 20.00 }
    ],
    created_at: formatDateTime(addDays(new Date(), -getRandomDaysAgo(1, 30))),
    updated_at: formatDateTime(addDays(new Date(), -getRandomDaysAgo(1, 25)))
  },
  {
    id: "demo-inv-021",
    xero_invoice_id: "demo-xero-inv-021",
    xero_contact_id: "demo-xero-015",
    invoice_number: "INV-2024-021",
    invoice_type: "ACCREC",
    invoice_status: "PAID",
    line_amount_types: "Exclusive",
    invoice_date: formatDate(addDays(new Date(), -getRandomDaysAgo(1, 30))),
    due_date: formatDate(addDays(new Date(), -getRandomDaysAgo(1, 30) + 30)),
    sub_total: 480.00,
    total_tax: 48.00,
    total: 528.00,
    total_discount: 0.00,
    amount_due: 0.00,
    amount_paid: 528.00,
    amount_credited: 0.00,
    fully_paid_on_date: formatDate(addDays(new Date(), -getRandomDaysAgo(1, 25))),
    work_description: "OE-24-0812 357 Hickory Ln | Emergency wasp nest removal | Large nest removal from eaves, safety equipment | Labour 3 hours | Materials: protective gear, pesticides",
    service_keywords: ["emergency service", "wasp removal", "nest removal", "safety"],
    line_items: [
      { Description: "Emergency call-out", Quantity: 1, UnitAmount: 150.00, LineAmount: 150.00 },
      { Description: "Wasp nest removal - large", Quantity: 1, UnitAmount: 200.00, LineAmount: 200.00 },
      { Description: "Safety equipment and pesticides", Quantity: 1, UnitAmount: 80.00, LineAmount: 80.00 },
      { Description: "Labour - 3 hours", Quantity: 3, UnitAmount: 16.67, LineAmount: 50.00 }
    ],
    created_at: formatDateTime(addDays(new Date(), -getRandomDaysAgo(1, 30))),
    updated_at: formatDateTime(addDays(new Date(), -getRandomDaysAgo(1, 25)))
  },
  {
    id: "demo-inv-022",
    xero_invoice_id: "demo-xero-inv-022",
    xero_contact_id: "demo-xero-015",
    invoice_number: "INV-2024-022",
    invoice_type: "ACCPAY",
    invoice_status: "PAID",
    line_amount_types: "Exclusive",
    invoice_date: "2024-08-10",
    due_date: "2024-08-20",
    sub_total: 120.00,
    total_tax: 12.00,
    total: 132.00,
    total_discount: 0.00,
    amount_due: 0.00,
    amount_paid: 132.00,
    amount_credited: 0.00,
    fully_paid_on_date: "2024-08-18",
    work_description: "Safety equipment and specialized pesticides for wasp removal",
    service_keywords: ["safety equipment", "pesticides", "wasp treatment", "supplies"],
    line_items: [
      { Description: "Protective suit rental", Quantity: 1, UnitAmount: 50.00, LineAmount: 50.00 },
      { Description: "Specialized wasp spray", Quantity: 2, UnitAmount: 35.00, LineAmount: 70.00 }
    ],
    created_at: "2024-08-10T10:00:00Z",
    updated_at: "2024-08-18T09:00:00Z"
  },
  {
    id: "demo-inv-023",
    xero_invoice_id: "demo-xero-inv-023",
    xero_contact_id: "demo-xero-016",
    invoice_number: "INV-2024-023",
    invoice_type: "ACCREC",
    invoice_status: "PAID",
    line_amount_types: "Exclusive",
    invoice_date: formatDate(addDays(new Date(), -getRandomDaysAgo(1, 30))),
    due_date: formatDate(addDays(new Date(), -getRandomDaysAgo(1, 30) + 30)),
    sub_total: 680.00,
    total_tax: 68.00,
    total: 748.00,
    total_discount: 0.00,
    amount_due: 0.00,
    amount_paid: 748.00,
    amount_credited: 0.00,
    fully_paid_on_date: formatDate(addDays(new Date(), -getRandomDaysAgo(1, 25))),
    work_description: "OE-24-0905 468 Dogwood Rd | Bathroom tile repair and caulking | Replaced broken tiles, recaulked tub and shower | Labour 6 hours | Materials: tiles, caulk, grout",
    service_keywords: ["bathroom repair", "tile replacement", "caulking", "grout work"],
    line_items: [
      { Description: "Tile replacement - 8 tiles", Quantity: 8, UnitAmount: 25.00, LineAmount: 200.00 },
      { Description: "Caulking and sealing", Quantity: 1, UnitAmount: 150.00, LineAmount: 150.00 },
      { Description: "Grout repair and cleaning", Quantity: 1, UnitAmount: 100.00, LineAmount: 100.00 },
      { Description: "Labour - 6 hours", Quantity: 6, UnitAmount: 38.33, LineAmount: 230.00 }
    ],
    created_at: formatDateTime(addDays(new Date(), -getRandomDaysAgo(1, 30))),
    updated_at: formatDateTime(addDays(new Date(), -getRandomDaysAgo(1, 25)))
  },
  {
    id: "demo-inv-024",
    xero_invoice_id: "demo-xero-inv-024",
    xero_contact_id: "demo-xero-016",
    invoice_number: "INV-2024-024",
    invoice_type: "ACCREC",
    invoice_status: "AUTHORISED",
    line_amount_types: "Exclusive",
    invoice_date: formatDate(addDays(new Date(), -getRandomDaysAgo(1, 30))),
    due_date: formatDate(addDays(new Date(), -getRandomDaysAgo(1, 30) + 30)),
    sub_total: 520.00,
    total_tax: 52.00,
    total: 572.00,
    total_discount: 0.00,
    amount_due: 572.00,
    amount_paid: 0.00,
    amount_credited: 0.00,
    work_description: "OE-24-1202 468 Dogwood Rd | Kitchen cabinet door adjustment and drawer repair | Adjusted 6 cabinet doors, repaired 2 drawers | Labour 4 hours | Materials: hinges, drawer slides",
    service_keywords: ["cabinet repair", "door adjustment", "drawer repair", "kitchen work"],
    line_items: [
      { Description: "Cabinet door adjustment - 6 doors", Quantity: 6, UnitAmount: 30.00, LineAmount: 180.00 },
      { Description: "Drawer repair and slides", Quantity: 2, UnitAmount: 80.00, LineAmount: 160.00 },
      { Description: "Hardware replacement", Quantity: 1, UnitAmount: 60.00, LineAmount: 60.00 },
      { Description: "Labour - 4 hours", Quantity: 4, UnitAmount: 30.00, LineAmount: 120.00 }
    ],
    created_at: formatDateTime(addDays(new Date(), -getRandomDaysAgo(1, 30))),
    updated_at: formatDateTime(addDays(new Date(), -getRandomDaysAgo(1, 30)))
  },
  {
    id: "demo-inv-025",
    xero_invoice_id: "demo-xero-inv-025",
    xero_contact_id: "demo-xero-017",
    invoice_number: "INV-2024-025",
    invoice_type: "ACCREC",
    invoice_status: "PAID",
    line_amount_types: "Exclusive",
    invoice_date: formatDate(addDays(new Date(), -getRandomDaysAgo(1, 30))),
    due_date: formatDate(addDays(new Date(), -getRandomDaysAgo(1, 30) + 30)),
    sub_total: 8500.00,
    total_tax: 850.00,
    total: 9350.00,
    total_discount: 0.00,
    amount_due: 0.00,
    amount_paid: 9350.00,
    amount_credited: 0.00,
    fully_paid_on_date: formatDate(addDays(new Date(), -getRandomDaysAgo(1, 25))),
    work_description: "OE-24-0515 579 Magnolia Way | Driveway concrete replacement | Removed old driveway, poured new concrete 40x20 ft | Labour 3 days | Materials: concrete, rebar, forms",
    service_keywords: ["concrete work", "driveway replacement", "excavation", "pouring"],
    line_items: [
      { Description: "Concrete removal and disposal", Quantity: 1, UnitAmount: 1500.00, LineAmount: 1500.00 },
      { Description: "Concrete - 800 sq ft", Quantity: 800, UnitAmount: 6.00, LineAmount: 4800.00 },
      { Description: "Rebar and forms", Quantity: 1, UnitAmount: 800.00, LineAmount: 800.00 },
      { Description: "Labour - 32 hours", Quantity: 32, UnitAmount: 43.75, LineAmount: 1400.00 }
    ],
    created_at: formatDateTime(addDays(new Date(), -getRandomDaysAgo(1, 30))),
    updated_at: formatDateTime(addDays(new Date(), -getRandomDaysAgo(1, 25)))
  },
  {
    id: "demo-inv-026",
    xero_invoice_id: "demo-xero-inv-026",
    xero_contact_id: "demo-xero-017",
    invoice_number: "INV-2024-026",
    invoice_type: "ACCREC",
    invoice_status: "PAID",
    line_amount_types: "Exclusive",
    invoice_date: formatDate(addDays(new Date(), -getRandomDaysAgo(1, 30))),
    due_date: formatDate(addDays(new Date(), -getRandomDaysAgo(1, 30) + 30)),
    sub_total: 6200.00,
    total_tax: 620.00,
    total: 6820.00,
    total_discount: 0.00,
    amount_due: 0.00,
    amount_paid: 6820.00,
    amount_credited: 0.00,
    fully_paid_on_date: formatDate(addDays(new Date(), -getRandomDaysAgo(1, 25))),
    work_description: "OE-24-0920 579 Magnolia Way | Backyard patio concrete pour | New patio 24x16 ft with decorative finish | Labour 2 days | Materials: concrete, stamping materials",
    service_keywords: ["patio concrete", "decorative finish", "stamping", "backyard"],
    line_items: [
      { Description: "Site preparation", Quantity: 1, UnitAmount: 800.00, LineAmount: 800.00 },
      { Description: "Concrete - 384 sq ft", Quantity: 384, UnitAmount: 8.00, LineAmount: 3072.00 },
      { Description: "Decorative stamping", Quantity: 384, UnitAmount: 4.00, LineAmount: 1536.00 },
      { Description: "Labour - 20 hours", Quantity: 20, UnitAmount: 39.60, LineAmount: 792.00 }
    ],
    created_at: formatDateTime(addDays(new Date(), -getRandomDaysAgo(1, 30))),
    updated_at: formatDateTime(addDays(new Date(), -getRandomDaysAgo(1, 25)))
  },
  {
    id: "demo-inv-027",
    xero_invoice_id: "demo-xero-inv-027",
    xero_contact_id: "demo-xero-017",
    invoice_number: "INV-2024-027",
    invoice_type: "ACCPAY",
    invoice_status: "PAID",
    line_amount_types: "Exclusive",
    invoice_date: "2024-09-18",
    due_date: "2024-09-28",
    sub_total: 1200.00,
    total_tax: 120.00,
    total: 1320.00,
    total_discount: 0.00,
    amount_due: 0.00,
    amount_paid: 1320.00,
    amount_credited: 0.00,
    fully_paid_on_date: "2024-09-25",
    work_description: "Concrete mixer truck rental and stamping tool rental for patio project",
    service_keywords: ["equipment rental", "concrete mixer", "stamping tools", "patio supplies"],
    line_items: [
      { Description: "Concrete mixer truck - 2 days", Quantity: 2, UnitAmount: 400.00, LineAmount: 800.00 },
      { Description: "Stamping tools rental", Quantity: 1, UnitAmount: 300.00, LineAmount: 300.00 },
      { Description: "Forms and stakes", Quantity: 1, UnitAmount: 100.00, LineAmount: 100.00 }
    ],
    created_at: "2024-09-18T08:00:00Z",
    updated_at: "2024-09-25T11:00:00Z"
  },
  {
    id: "demo-inv-028",
    xero_invoice_id: "demo-xero-inv-028",
    xero_contact_id: "demo-xero-018",
    invoice_number: "INV-2024-028",
    invoice_type: "ACCREC",
    invoice_status: "PAID",
    line_amount_types: "Exclusive",
    invoice_date: formatDate(addDays(new Date(), -getRandomDaysAgo(1, 30))),
    due_date: formatDate(addDays(new Date(), -getRandomDaysAgo(1, 30) + 30)),
    sub_total: 2200.00,
    total_tax: 220.00,
    total: 2420.00,
    total_discount: 0.00,
    amount_due: 0.00,
    amount_paid: 2420.00,
    amount_credited: 0.00,
    fully_paid_on_date: formatDate(addDays(new Date(), -getRandomDaysAgo(1, 25))),
    work_description: "OE-24-0315 680 Sycamore St | Large oak tree removal | Emergency removal after storm damage | Labour 8 hours | Materials: safety equipment, disposal",
    service_keywords: ["tree removal", "emergency service", "storm damage", "large tree"],
    line_items: [
      { Description: "Emergency tree assessment", Quantity: 1, UnitAmount: 200.00, LineAmount: 200.00 },
      { Description: "Large tree removal", Quantity: 1, UnitAmount: 1400.00, LineAmount: 1400.00 },
      { Description: "Cleanup and disposal", Quantity: 1, UnitAmount: 300.00, LineAmount: 300.00 },
      { Description: "Labour - 8 hours", Quantity: 8, UnitAmount: 37.50, LineAmount: 300.00 }
    ],
    created_at: formatDateTime(addDays(new Date(), -getRandomDaysAgo(1, 30))),
    updated_at: formatDateTime(addDays(new Date(), -getRandomDaysAgo(1, 25)))
  },
  {
    id: "demo-inv-029",
    xero_invoice_id: "demo-xero-inv-029",
    xero_contact_id: "demo-xero-018",
    invoice_number: "INV-2024-029",
    invoice_type: "ACCREC",
    invoice_status: "PAID",
    line_amount_types: "Exclusive",
    invoice_date: formatDate(addDays(new Date(), -getRandomDaysAgo(1, 30))),
    due_date: formatDate(addDays(new Date(), -getRandomDaysAgo(1, 30) + 30)),
    sub_total: 850.00,
    total_tax: 85.00,
    total: 935.00,
    total_discount: 0.00,
    amount_due: 0.00,
    amount_paid: 935.00,
    amount_credited: 0.00,
    fully_paid_on_date: formatDate(addDays(new Date(), -getRandomDaysAgo(1, 25))),
    work_description: "OE-24-1008 680 Sycamore St | Tree trimming and pruning | Trimmed 4 trees, pruned overgrown branches | Labour 6 hours | Materials: safety equipment",
    service_keywords: ["tree trimming", "pruning", "maintenance", "safety"],
    line_items: [
      { Description: "Tree trimming - 4 trees", Quantity: 4, UnitAmount: 150.00, LineAmount: 600.00 },
      { Description: "Branch pruning and shaping", Quantity: 1, UnitAmount: 150.00, LineAmount: 150.00 },
      { Description: "Cleanup and disposal", Quantity: 1, UnitAmount: 50.00, LineAmount: 50.00 },
      { Description: "Labour - 6 hours", Quantity: 6, UnitAmount: 8.33, LineAmount: 50.00 }
    ],
    created_at: formatDateTime(addDays(new Date(), -getRandomDaysAgo(1, 30))),
    updated_at: formatDateTime(addDays(new Date(), -getRandomDaysAgo(1, 25)))
  },
  {
    id: "demo-inv-030",
    xero_invoice_id: "demo-xero-inv-030",
    xero_contact_id: "demo-xero-019",
    invoice_number: "INV-2024-030",
    invoice_type: "ACCREC",
    invoice_status: "PAID",
    line_amount_types: "Exclusive",
    invoice_date: formatDate(addDays(new Date(), -getRandomDaysAgo(1, 30))),
    due_date: formatDate(addDays(new Date(), -getRandomDaysAgo(1, 30) + 30)),
    sub_total: 1200.00,
    total_tax: 120.00,
    total: 1320.00,
    total_discount: 0.00,
    amount_due: 0.00,
    amount_paid: 1320.00,
    amount_credited: 0.00,
    fully_paid_on_date: formatDate(addDays(new Date(), -getRandomDaysAgo(1, 25))),
    work_description: "OE-24-0822 791 Redwood Dr | Local residential move | 3-bedroom house, full packing and moving service | Labour 8 hours | Materials: boxes, packing materials",
    service_keywords: ["residential move", "packing service", "local move", "full service"],
    line_items: [
      { Description: "Packing service - 3 bedrooms", Quantity: 1, UnitAmount: 400.00, LineAmount: 400.00 },
      { Description: "Moving truck and crew - 8 hours", Quantity: 8, UnitAmount: 75.00, LineAmount: 600.00 },
      { Description: "Packing materials", Quantity: 1, UnitAmount: 150.00, LineAmount: 150.00 },
      { Description: "Labour - 8 hours", Quantity: 8, UnitAmount: 6.25, LineAmount: 50.00 }
    ],
    created_at: formatDateTime(addDays(new Date(), -getRandomDaysAgo(1, 30))),
    updated_at: formatDateTime(addDays(new Date(), -getRandomDaysAgo(1, 25)))
  },
  {
    id: "demo-inv-031",
    xero_invoice_id: "demo-xero-inv-031",
    xero_contact_id: "demo-xero-019",
    invoice_number: "INV-2024-031",
    invoice_type: "ACCREC",
    invoice_status: "AUTHORISED",
    line_amount_types: "Exclusive",
    invoice_date: formatDate(addDays(new Date(), -getRandomDaysAgo(1, 30))),
    due_date: formatDate(addDays(new Date(), -getRandomDaysAgo(1, 30) + 30)),
    sub_total: 800.00,
    total_tax: 80.00,
    total: 880.00,
    total_discount: 0.00,
    amount_due: 880.00,
    amount_paid: 0.00,
    amount_credited: 0.00,
    work_description: "OE-24-1115 791 Redwood Dr | Piano moving service | Specialty move of baby grand piano | Labour 4 hours | Materials: piano moving equipment",
    service_keywords: ["piano moving", "specialty move", "heavy equipment", "careful handling"],
    line_items: [
      { Description: "Piano moving - baby grand", Quantity: 1, UnitAmount: 500.00, LineAmount: 500.00 },
      { Description: "Specialty equipment rental", Quantity: 1, UnitAmount: 150.00, LineAmount: 150.00 },
      { Description: "Insurance coverage", Quantity: 1, UnitAmount: 100.00, LineAmount: 100.00 },
      { Description: "Labour - 4 hours", Quantity: 4, UnitAmount: 12.50, LineAmount: 50.00 }
    ],
    created_at: formatDateTime(addDays(new Date(), -getRandomDaysAgo(1, 30))),
    updated_at: formatDateTime(addDays(new Date(), -getRandomDaysAgo(1, 30)))
  },
  {
    id: "demo-inv-032",
    xero_invoice_id: "demo-xero-inv-032",
    xero_contact_id: "demo-xero-020",
    invoice_number: "INV-2024-032",
    invoice_type: "ACCREC",
    invoice_status: "PAID",
    line_amount_types: "Exclusive",
    invoice_date: formatDate(addDays(new Date(), -getRandomDaysAgo(1, 30))),
    due_date: formatDate(addDays(new Date(), -getRandomDaysAgo(1, 30) + 30)),
    sub_total: 350.00,
    total_tax: 35.00,
    total: 385.00,
    total_discount: 0.00,
    amount_due: 0.00,
    amount_paid: 385.00,
    amount_credited: 0.00,
    fully_paid_on_date: formatDate(addDays(new Date(), -getRandomDaysAgo(1, 25))),
    work_description: "OE-24-0703 802 Cypress Ave | Full exterior car detailing | Wash, clay bar, polish, wax | Labour 4 hours | Materials: detailing supplies",
    service_keywords: ["auto detailing", "exterior detailing", "polish", "wax"],
    line_items: [
      { Description: "Full exterior wash", Quantity: 1, UnitAmount: 80.00, LineAmount: 80.00 },
      { Description: "Clay bar treatment", Quantity: 1, UnitAmount: 100.00, LineAmount: 100.00 },
      { Description: "Polish and wax", Quantity: 1, UnitAmount: 120.00, LineAmount: 120.00 },
      { Description: "Labour - 4 hours", Quantity: 4, UnitAmount: 12.50, LineAmount: 50.00 }
    ],
    created_at: formatDateTime(addDays(new Date(), -getRandomDaysAgo(1, 30))),
    updated_at: formatDateTime(addDays(new Date(), -getRandomDaysAgo(1, 25)))
  },
  {
    id: "demo-inv-033",
    xero_invoice_id: "demo-xero-inv-033",
    xero_contact_id: "demo-xero-020",
    invoice_number: "INV-2024-033",
    invoice_type: "ACCREC",
    invoice_status: "PAID",
    line_amount_types: "Exclusive",
    invoice_date: formatDate(addDays(new Date(), -getRandomDaysAgo(1, 30))),
    due_date: formatDate(addDays(new Date(), -getRandomDaysAgo(1, 30) + 30)),
    sub_total: 250.00,
    total_tax: 25.00,
    total: 275.00,
    total_discount: 0.00,
    amount_due: 0.00,
    amount_paid: 275.00,
    amount_credited: 0.00,
    fully_paid_on_date: formatDate(addDays(new Date(), -getRandomDaysAgo(1, 25))),
    work_description: "OE-24-0910 802 Cypress Ave | Interior car detailing | Vacuum, shampoo, leather treatment | Labour 3 hours | Materials: cleaning supplies",
    service_keywords: ["interior detailing", "vacuum", "shampoo", "leather treatment"],
    line_items: [
      { Description: "Interior vacuum and cleaning", Quantity: 1, UnitAmount: 80.00, LineAmount: 80.00 },
      { Description: "Upholstery shampoo", Quantity: 1, UnitAmount: 100.00, LineAmount: 100.00 },
      { Description: "Leather treatment", Quantity: 1, UnitAmount: 50.00, LineAmount: 50.00 },
      { Description: "Labour - 3 hours", Quantity: 3, UnitAmount: 6.67, LineAmount: 20.00 }
    ],
    created_at: formatDateTime(addDays(new Date(), -getRandomDaysAgo(1, 30))),
    updated_at: formatDateTime(addDays(new Date(), -getRandomDaysAgo(1, 25)))
  },
  {
    id: "demo-inv-034",
    xero_invoice_id: "demo-xero-inv-034",
    xero_contact_id: "demo-xero-020",
    invoice_number: "INV-2024-034",
    invoice_type: "ACCPAY",
    invoice_status: "PAID",
    line_amount_types: "Exclusive",
    invoice_date: "2024-07-01",
    due_date: "2024-07-11",
    sub_total: 180.00,
    total_tax: 18.00,
    total: 198.00,
    total_discount: 0.00,
    amount_due: 0.00,
    amount_paid: 198.00,
    amount_credited: 0.00,
    fully_paid_on_date: "2024-07-08",
    work_description: "Professional detailing supplies and equipment",
    service_keywords: ["detailing supplies", "professional equipment", "car care products"],
    line_items: [
      { Description: "Premium car wax - 6 bottles", Quantity: 6, UnitAmount: 15.00, LineAmount: 90.00 },
      { Description: "Microfiber cloths - 20 pack", Quantity: 2, UnitAmount: 25.00, LineAmount: 50.00 },
      { Description: "Clay bar kit", Quantity: 2, UnitAmount: 20.00, LineAmount: 40.00 }
    ],
    created_at: "2024-07-01T10:00:00Z",
    updated_at: "2024-07-08T12:00:00Z"
  },
  {
    id: "demo-inv-035",
    xero_invoice_id: "demo-xero-inv-035",
    xero_contact_id: "demo-xero-001",
    invoice_number: "INV-2024-035",
    invoice_type: "ACCREC",
    invoice_status: "PAID",
    line_amount_types: "Exclusive",
    invoice_date: formatDate(addDays(new Date(), -getRandomDaysAgo(1, 30))),
    due_date: formatDate(addDays(new Date(), -getRandomDaysAgo(1, 30) + 30)),
    sub_total: 1200.00,
    total_tax: 120.00,
    total: 1320.00,
    total_discount: 0.00,
    amount_due: 0.00,
    amount_paid: 1320.00,
    amount_credited: 0.00,
    fully_paid_on_date: formatDate(addDays(new Date(), -getRandomDaysAgo(1, 25))),
    work_description: "OE-24-0610 123 Main St | Bathroom renovation plumbing | New vanity plumbing, toilet installation | Labour 6 hours | Materials: pipes, fittings, toilet",
    service_keywords: ["bathroom renovation", "vanity plumbing", "toilet installation", "new construction"],
    line_items: [
      { Description: "Vanity plumbing installation", Quantity: 1, UnitAmount: 400.00, LineAmount: 400.00 },
      { Description: "Toilet installation", Quantity: 1, UnitAmount: 300.00, LineAmount: 300.00 },
      { Description: "Pipes and fittings", Quantity: 1, UnitAmount: 200.00, LineAmount: 200.00 },
      { Description: "Labour - 6 hours", Quantity: 6, UnitAmount: 50.00, LineAmount: 300.00 }
    ],
    created_at: formatDateTime(addDays(new Date(), -getRandomDaysAgo(1, 30))),
    updated_at: formatDateTime(addDays(new Date(), -getRandomDaysAgo(1, 25)))
  },
  {
    id: "demo-inv-036",
    xero_invoice_id: "demo-xero-inv-036",
    xero_contact_id: "demo-xero-001",
    invoice_number: "INV-2024-036",
    invoice_type: "ACCPAY",
    invoice_status: "PAID",
    line_amount_types: "Exclusive",
    invoice_date: "2024-06-08",
    due_date: "2024-06-18",
    sub_total: 250.00,
    total_tax: 25.00,
    total: 275.00,
    total_discount: 0.00,
    amount_due: 0.00,
    amount_paid: 275.00,
    amount_credited: 0.00,
    fully_paid_on_date: "2024-06-15",
    work_description: "Plumbing supplies for bathroom renovation project",
    service_keywords: ["plumbing supplies", "bathroom materials", "renovation supplies"],
    line_items: [
      { Description: "High-efficiency toilet", Quantity: 1, UnitAmount: 180.00, LineAmount: 180.00 },
      { Description: "Copper fittings", Quantity: 1, UnitAmount: 70.00, LineAmount: 70.00 }
    ],
    created_at: "2024-06-08T09:00:00Z",
    updated_at: "2024-06-15T11:00:00Z"
  },
  {
    id: "demo-inv-037",
    xero_invoice_id: "demo-xero-inv-037",
    xero_contact_id: "demo-xero-002",
    invoice_number: "INV-2024-037",
    invoice_type: "ACCREC",
    invoice_status: "PAID",
    line_amount_types: "Exclusive",
    invoice_date: formatDate(addDays(new Date(), -getRandomDaysAgo(1, 30))),
    due_date: formatDate(addDays(new Date(), -getRandomDaysAgo(1, 30) + 30)),
    sub_total: 800.00,
    total_tax: 80.00,
    total: 880.00,
    total_discount: 0.00,
    amount_due: 0.00,
    amount_paid: 880.00,
    amount_credited: 0.00,
    fully_paid_on_date: formatDate(addDays(new Date(), -getRandomDaysAgo(1, 25))),
    work_description: "OE-24-0505 456 Oak Ave | Outdoor lighting installation | Landscape lighting, security lights | Labour 5 hours | Materials: fixtures, wire, conduit",
    service_keywords: ["outdoor lighting", "landscape lighting", "security lights", "installation"],
    line_items: [
      { Description: "Landscape light fixtures - 8 units", Quantity: 8, UnitAmount: 50.00, LineAmount: 400.00 },
      { Description: "Security flood lights - 2 units", Quantity: 2, UnitAmount: 80.00, LineAmount: 160.00 },
      { Description: "Wire and conduit", Quantity: 1, UnitAmount: 100.00, LineAmount: 100.00 },
      { Description: "Labour - 5 hours", Quantity: 5, UnitAmount: 28.00, LineAmount: 140.00 }
    ],
    created_at: formatDateTime(addDays(new Date(), -getRandomDaysAgo(1, 30))),
    updated_at: formatDateTime(addDays(new Date(), -getRandomDaysAgo(1, 25)))
  },
  {
    id: "demo-inv-038",
    xero_invoice_id: "demo-xero-inv-038",
    xero_contact_id: "demo-xero-002",
    invoice_number: "INV-2024-038",
    invoice_type: "ACCPAY",
    invoice_status: "PAID",
    line_amount_types: "Exclusive",
    invoice_date: "2024-05-03",
    due_date: "2024-05-13",
    sub_total: 320.00,
    total_tax: 32.00,
    total: 352.00,
    total_discount: 0.00,
    amount_due: 0.00,
    amount_paid: 352.00,
    amount_credited: 0.00,
    fully_paid_on_date: "2024-05-10",
    work_description: "Electrical supplies for outdoor lighting project",
    service_keywords: ["electrical supplies", "lighting materials", "outdoor equipment"],
    line_items: [
      { Description: "LED landscape fixtures", Quantity: 8, UnitAmount: 30.00, LineAmount: 240.00 },
      { Description: "Outdoor rated wire - 200 ft", Quantity: 200, UnitAmount: 0.40, LineAmount: 80.00 }
    ],
    created_at: "2024-05-03T10:00:00Z",
    updated_at: "2024-05-10T14:00:00Z"
  },
  {
    id: "demo-inv-039",
    xero_invoice_id: "demo-xero-inv-039",
    xero_contact_id: "demo-xero-003",
    invoice_number: "INV-2024-039",
    invoice_type: "ACCREC",
    invoice_status: "AUTHORISED",
    line_amount_types: "Exclusive",
    invoice_date: formatDate(addDays(new Date(), -getRandomDaysAgo(1, 30))),
    due_date: formatDate(addDays(new Date(), -getRandomDaysAgo(1, 30) + 30)),
    sub_total: 1500.00,
    total_tax: 150.00,
    total: 1650.00,
    total_discount: 0.00,
    amount_due: 1650.00,
    amount_paid: 0.00,
    amount_credited: 0.00,
    work_description: "OE-24-1205 789 Pine Rd | Spring garden design and planting | New flower beds, tree planting, irrigation | Labour 12 hours | Materials: plants, mulch, irrigation supplies",
    service_keywords: ["garden design", "spring planting", "flower beds", "irrigation"],
    line_items: [
      { Description: "Garden design consultation", Quantity: 1, UnitAmount: 300.00, LineAmount: 300.00 },
      { Description: "Plants and flowers", Quantity: 1, UnitAmount: 500.00, LineAmount: 500.00 },
      { Description: "Mulch and soil amendments", Quantity: 1, UnitAmount: 200.00, LineAmount: 200.00 },
      { Description: "Labour - 12 hours", Quantity: 12, UnitAmount: 41.67, LineAmount: 500.00 }
    ],
    created_at: formatDateTime(addDays(new Date(), -getRandomDaysAgo(1, 30))),
    updated_at: formatDateTime(addDays(new Date(), -getRandomDaysAgo(1, 30)))
  },
  {
    id: "demo-inv-040",
    xero_invoice_id: "demo-xero-inv-040",
    xero_contact_id: "demo-xero-004",
    invoice_number: "INV-2024-040",
    invoice_type: "ACCREC",
    invoice_status: "AUTHORISED",
    line_amount_types: "Exclusive",
    invoice_date: formatDate(addDays(new Date(), -getRandomDaysAgo(1, 30))),
    due_date: formatDate(addDays(new Date(), -getRandomDaysAgo(1, 30) + 30)),
    sub_total: 2800.00,
    total_tax: 280.00,
    total: 3080.00,
    total_discount: 0.00,
    amount_due: 3080.00,
    amount_paid: 0.00,
    amount_credited: 0.00,
    work_description: "OE-24-1210 321 Elm St | Furnace replacement | Old furnace removal, new high-efficiency unit installation | Labour 8 hours | Materials: furnace, ductwork modifications",
    service_keywords: ["furnace replacement", "high efficiency", "installation", "ductwork"],
    line_items: [
      { Description: "High-efficiency furnace unit", Quantity: 1, UnitAmount: 2000.00, LineAmount: 2000.00 },
      { Description: "Old unit removal and disposal", Quantity: 1, UnitAmount: 300.00, LineAmount: 300.00 },
      { Description: "Ductwork modifications", Quantity: 1, UnitAmount: 200.00, LineAmount: 200.00 },
      { Description: "Labour - 8 hours", Quantity: 8, UnitAmount: 37.50, LineAmount: 300.00 }
    ],
    created_at: formatDateTime(addDays(new Date(), -getRandomDaysAgo(1, 30))),
    updated_at: formatDateTime(addDays(new Date(), -getRandomDaysAgo(1, 30)))
  }
];
