// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qbajyluwdjtztraslwdk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFiYWp5bHV3ZGp0enRyYXNsd2RrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1MDMyMzksImV4cCI6MjA2NDA3OTIzOX0.w-94n-cWksOw6rbnjehMEPrXtCnOlybXUQSImQb8Tck";

export const projectRef = new URL(SUPABASE_URL).hostname.split('.')[0];

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
