// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bjfzwlosdgtowruvvaei.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJqZnp3bG9zZGd0b3dydXZ2YWVpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4Nzc0NzUsImV4cCI6MjA2NzQ1MzQ3NX0.AV_6ZpRJ0YCrLv7ClUrcREEwqMkZ3A3A5eHzv-ZsqG0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});