
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bjfzwlosdgtowruvvaei.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJqZnp3bG9zZGd0b3dydXV2dmFlaSIsInJvbGUiOiJhbm9uIiwiaWF0IjoxNzUxODc3NDc1LCJleHAiOjIwNjc0NTM0NzV9.AV_6ZpRJ0YCrLv7ClUrcREEwqMkZ3A3A5eHzv-ZsqG0";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Export project reference for components that need it
export const projectRef = "bjfzwlosdgtowruvvaei";
